#!/bin/sh
# Assemble the ARM7 HLE BIOS and regenerate rtl/nds_bios7.vhd.
# Needs devkitARM (arm-none-eabi) on the host — run locally, the
# generated VHDL is checked in.
set -eu
cd "$(dirname "$0")"

DKA=/opt/devkitpro/devkitARM/bin
$DKA/arm-none-eabi-as -mcpu=arm7tdmi -o bios7.o bios7.s
$DKA/arm-none-eabi-ld -Ttext=0 -o bios7.elf bios7.o
$DKA/arm-none-eabi-objcopy -O binary bios7.elf bios7.bin
$DKA/arm-none-eabi-objdump -d bios7.elf > bios7.lst

python3 - "$(cd ../../.. && pwd)/rtl/nds_bios7.vhd" <<'EOF'
import struct, sys

words = []
with open("bios7.bin", "rb") as f:
    data = f.read()
data += b"\0" * (-len(data) % 4)
for i in range(0, len(data), 4):
    words.append(struct.unpack_from("<I", data, i)[0])

dis = {}
with open("bios7.lst") as f:
    for line in f:
        line = line.rstrip()
        parts = line.split("\t")
        if len(parts) >= 3 and parts[0].strip().endswith(":"):
            try:
                adr = int(parts[0].strip()[:-1], 16)
            except ValueError:
                continue
            dis[adr] = "\t".join(p.strip() for p in parts[2:])

out = sys.argv[1]
with open(out, "w") as f:
    f.write("""-- SPDX-License-Identifier: GPL-2.0-or-later
-- ARM7 HLE BIOS ROM — GENERATED by sim/tests/hle_bios7/build.sh from
-- bios7.s, do not edit. Served at 0x00000000 through nds_membus7's
-- bios port (address registered there, data combinational here).

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity nds_bios7 is
   port
   (
      bios_addr : in  unsigned(13 downto 2);
      bios_data : out std_logic_vector(31 downto 0)
   );
end entity;

architecture arch of nds_bios7 is

""")
    f.write("   type t_rom is array (0 to %d) of std_logic_vector(31 downto 0);\n" % (len(words) - 1))
    f.write("   constant ROM : t_rom := (\n")
    for i, w in enumerate(words):
        sep = "," if i < len(words) - 1 else " "
        note = dis.get(i * 4, "")
        f.write('      x"%08X"%s  -- 0x%02X  %s\n' % (w, sep, i * 4, note))
    f.write("""   );

begin

   bios_data <= ROM(to_integer(bios_addr)) when (to_integer(bios_addr) <= t_rom'high)
                else x"00000000";

end architecture;
""")
print("wrote", out, "-", len(words), "words")
EOF

rm -f bios7.o bios7.elf bios7.bin bios7.lst
