-- SPDX-License-Identifier: GPL-2.0-or-later
-- ARM7 HLE BIOS ROM — GENERATED by sim/tests/hle_bios7/build.sh from
-- bios7.s, do not edit. Served at 0x00000000 through nds_membus7's
-- bios port (address registered there, data combinational here).

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity nds_bios7 is
   port
   (
      bios_addr : in  unsigned(13 downto 2);
      bios_data : out std_logic_vector(31 downto 0)
   );
end entity;

architecture arch of nds_bios7 is

   type t_rom is array (0 to 92) of std_logic_vector(31 downto 0);
   constant ROM : t_rom := (
      x"EAFFFFFE",  -- 0x00  b	0 <vec_reset>
      x"EAFFFFFE",  -- 0x04  b	4 <vec_undef>
      x"EA00000A",  -- 0x08  b	38 <swi_handler>
      x"EAFFFFFE",  -- 0x0C  b	c <vec_pabt>
      x"EAFFFFFE",  -- 0x10  b	10 <vec_dabt>
      x"EAFFFFFE",  -- 0x14  b	14 <vec_resv>
      x"EA000000",  -- 0x18  b	20 <irq_handler>
      x"EAFFFFFE",  -- 0x1C  b	1c <vec_fiq>
      x"E92D500F",  -- 0x20  push	{r0, r1, r2, r3, ip, lr}
      x"E59FC140",  -- 0x24  ldr	ip, [pc, #320]	@ 16c <swi_getcrc16+0x2c>
      x"E28FE000",  -- 0x28  add	lr, pc, #0
      x"E59CF000",  -- 0x2C  ldr	pc, [ip]
      x"E8BD500F",  -- 0x30  pop	{r0, r1, r2, r3, ip, lr}
      x"E25EF004",  -- 0x34  subs	pc, lr, #4
      x"E92D5800",  -- 0x38  push	{fp, ip, lr}
      x"E14FC000",  -- 0x3C  mrs	ip, SPSR
      x"E31C0020",  -- 0x40  tst	ip, #32
      x"155EB002",  -- 0x44  ldrbne	fp, [lr, #-2]
      x"051EB004",  -- 0x48  ldreq	fp, [lr, #-4]
      x"01A0B82B",  -- 0x4C  lsreq	fp, fp, #16
      x"E20BB0FF",  -- 0x50  and	fp, fp, #255	@ 0xff
      x"E35B0003",  -- 0x54  cmp	fp, #3
      x"0A000010",  -- 0x58  beq	a0 <swi_waitbyloop>
      x"E35B0006",  -- 0x5C  cmp	fp, #6
      x"0A000011",  -- 0x60  beq	ac <swi_halt>
      x"E35B0007",  -- 0x64  cmp	fp, #7
      x"0A00000F",  -- 0x68  beq	ac <swi_halt>
      x"E35B0008",  -- 0x6C  cmp	fp, #8
      x"0A000008",  -- 0x70  beq	98 <swi_ret>
      x"E35B0009",  -- 0x74  cmp	fp, #9
      x"0A000012",  -- 0x78  beq	c8 <swi_div>
      x"E35B000E",  -- 0x7C  cmp	fp, #14
      x"0A00002E",  -- 0x80  beq	140 <swi_getcrc16>
      x"E35B000F",  -- 0x84  cmp	fp, #15
      x"0A00002A",  -- 0x88  beq	138 <swi_isdebugger>
      x"E35B001F",  -- 0x8C  cmp	fp, #31
      x"0A000009",  -- 0x90  beq	bc <swi_customhalt>
      x"EAFFFFFE",  -- 0x94  b	94 <swi_bad>
      x"E8BD5800",  -- 0x98  pop	{fp, ip, lr}
      x"E1B0F00E",  -- 0x9C  movs	pc, lr
      x"E2500001",  -- 0xA0  subs	r0, r0, #1
      x"CAFFFFFD",  -- 0xA4  bgt	a0 <swi_waitbyloop>
      x"EAFFFFFA",  -- 0xA8  b	98 <swi_ret>
      x"E3A0C301",  -- 0xAC  mov	ip, #67108864	@ 0x4000000
      x"E3A0B080",  -- 0xB0  mov	fp, #128	@ 0x80
      x"E5CCB301",  -- 0xB4  strb	fp, [ip, #769]	@ 0x301
      x"EAFFFFF6",  -- 0xB8  b	98 <swi_ret>
      x"E3A0C301",  -- 0xBC  mov	ip, #67108864	@ 0x4000000
      x"E5CC2301",  -- 0xC0  strb	r2, [ip, #769]	@ 0x301
      x"EAFFFFF3",  -- 0xC4  b	98 <swi_ret>
      x"E92D0034",  -- 0xC8  push	{r2, r4, r5}
      x"E1B04000",  -- 0xCC  movs	r4, r0
      x"42600000",  -- 0xD0  rsbmi	r0, r0, #0
      x"E1B05001",  -- 0xD4  movs	r5, r1
      x"42611000",  -- 0xD8  rsbmi	r1, r1, #0
      x"E3A02000",  -- 0xDC  mov	r2, #0
      x"E3510000",  -- 0xE0  cmp	r1, #0
      x"0A00000A",  -- 0xE4  beq	114 <swi_div+0x4c>
      x"E3A0C001",  -- 0xE8  mov	ip, #1
      x"E15100A0",  -- 0xEC  cmp	r1, r0, lsr #1
      x"91A01081",  -- 0xF0  lslls	r1, r1, #1
      x"91A0C08C",  -- 0xF4  lslls	ip, ip, #1
      x"9AFFFFFB",  -- 0xF8  bls	ec <swi_div+0x24>
      x"E1500001",  -- 0xFC  cmp	r0, r1
      x"20400001",  -- 0x100  subcs	r0, r0, r1
      x"2182200C",  -- 0x104  orrcs	r2, r2, ip
      x"E1B0C0AC",  -- 0x108  lsrs	ip, ip, #1
      x"11A010A1",  -- 0x10C  lsrne	r1, r1, #1
      x"1AFFFFF9",  -- 0x110  bne	fc <swi_div+0x34>
      x"E1A03002",  -- 0x114  mov	r3, r2
      x"E1340005",  -- 0x118  teq	r4, r5
      x"42622000",  -- 0x11C  rsbmi	r2, r2, #0
      x"E1B04004",  -- 0x120  movs	r4, r4
      x"42600000",  -- 0x124  rsbmi	r0, r0, #0
      x"E1A01000",  -- 0x128  mov	r1, r0
      x"E1A00002",  -- 0x12C  mov	r0, r2
      x"E8BD0034",  -- 0x130  pop	{r2, r4, r5}
      x"EAFFFFD7",  -- 0x134  b	98 <swi_ret>
      x"E3A00000",  -- 0x138  mov	r0, #0
      x"EAFFFFD5",  -- 0x13C  b	98 <swi_ret>
      x"E59FC028",  -- 0x140  ldr	ip, [pc, #40]	@ 170 <swi_getcrc16+0x30>
      x"E2522001",  -- 0x144  subs	r2, r2, #1
      x"BAFFFFD2",  -- 0x148  blt	98 <swi_ret>
      x"E4D1B001",  -- 0x14C  ldrb	fp, [r1], #1
      x"E020000B",  -- 0x150  eor	r0, r0, fp
      x"E3A0B008",  -- 0x154  mov	fp, #8
      x"E1B000A0",  -- 0x158  lsrs	r0, r0, #1
      x"2020000C",  -- 0x15C  eorcs	r0, r0, ip
      x"E25BB001",  -- 0x160  subs	fp, fp, #1
      x"1AFFFFFB",  -- 0x164  bne	158 <swi_getcrc16+0x18>
      x"EAFFFFF5",  -- 0x168  b	144 <swi_getcrc16+0x4>
      x"0380FFFC",  -- 0x16C  .word	0x0380fffc
      x"0000A001"   -- 0x170  .word	0x0000a001
   );

begin

   bios_data <= ROM(to_integer(bios_addr)) when (to_integer(bios_addr) <= t_rom'high)
                else x"00000000";

end architecture;
