#!/bin/sh
# Assemble the ARM9 HLE BIOS and regenerate rtl/nds_bios9.vhd.
# Needs devkitARM (arm-none-eabi) on the host — run locally, the
# generated VHDL is checked in.
set -eu
cd "$(dirname "$0")"

DKA=/opt/devkitpro/devkitARM/bin
$DKA/arm-none-eabi-as -mcpu=arm946e-s -o bios9.o bios9.s
$DKA/arm-none-eabi-ld -Ttext=0xFFFF0000 -o bios9.elf bios9.o
$DKA/arm-none-eabi-objcopy -O binary bios9.elf bios9.bin
$DKA/arm-none-eabi-objdump -d bios9.elf > bios9.lst

python3 - "$(cd ../../.. && pwd)/rtl/nds_bios9.vhd" <<'EOF'
import struct, sys

words = []
with open("bios9.bin", "rb") as f:
    data = f.read()
data += b"\0" * (-len(data) % 4)
for i in range(0, len(data), 4):
    words.append(struct.unpack_from("<I", data, i)[0])

dis = {}
with open("bios9.lst") as f:
    for line in f:
        line = line.rstrip()
        parts = line.split("\t")
        if len(parts) >= 3 and parts[0].strip().endswith(":"):
            try:
                adr = int(parts[0].strip()[:-1], 16)
            except ValueError:
                continue
            dis[adr - 0xFFFF0000] = "\t".join(p.strip() for p in parts[2:])

out = sys.argv[1]
with open(out, "w") as f:
    f.write("""-- SPDX-License-Identifier: GPL-2.0-or-later
-- ARM9 HLE BIOS ROM — GENERATED by sim/tests/hle_bios9/build.sh from
-- bios9.s, do not edit. Served at 0xFFFF0000 (NDS9 high-vector boot
-- ROM window) through nds_membus9's brom port.

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity nds_bios9 is
   port
   (
      brom_addr : in  unsigned(14 downto 2);
      brom_data : out std_logic_vector(31 downto 0)
   );
end entity;

architecture arch of nds_bios9 is

""")
    f.write("   type t_rom is array (0 to %d) of std_logic_vector(31 downto 0);\n" % (len(words) - 1))
    f.write("   constant ROM : t_rom := (\n")
    for i, w in enumerate(words):
        sep = "," if i < len(words) - 1 else " "
        note = dis.get(i * 4, "")
        f.write('      x"%08X"%s  -- 0x%02X  %s\n' % (w, sep, i * 4, note))
    f.write("""   );

begin

   brom_data <= ROM(to_integer(brom_addr)) when (to_integer(brom_addr) <= t_rom'high)
                else x"00000000";

end architecture;
""")
print("wrote", out, "-", len(words), "words")
EOF

rm -f bios9.o bios9.elf bios9.bin bios9.lst
